// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnH0fJNXGIYVVqb7msH4hgex4atHEaL3c',
    appId: '1:232470263206:web:dc8725eec30029d117cb67',
    messagingSenderId: '232470263206',
    projectId: 'fyp-sensor-13370',
    authDomain: 'fyp-sensor-13370.firebaseapp.com',
    databaseURL: 'https://fyp-sensor-13370-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp-sensor-13370.firebasestorage.app',
    measurementId: 'G-CXEFRZT6VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0fNie_ecpp0Pq6bGUaB55iBIAqgMUHjs',
    appId: '1:232470263206:android:5b3f9f752f9c4b0617cb67',
    messagingSenderId: '232470263206',
    projectId: 'fyp-sensor-13370',
    databaseURL: 'https://fyp-sensor-13370-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp-sensor-13370.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9z94-FUWx4NiQ8JuGVM4JhD2u49NkXf8',
    appId: '1:232470263206:ios:bafe6b1ba6b935fb17cb67',
    messagingSenderId: '232470263206',
    projectId: 'fyp-sensor-13370',
    databaseURL: 'https://fyp-sensor-13370-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp-sensor-13370.firebasestorage.app',
    iosBundleId: 'com.example.activesyncApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9z94-FUWx4NiQ8JuGVM4JhD2u49NkXf8',
    appId: '1:232470263206:ios:bafe6b1ba6b935fb17cb67',
    messagingSenderId: '232470263206',
    projectId: 'fyp-sensor-13370',
    databaseURL: 'https://fyp-sensor-13370-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp-sensor-13370.firebasestorage.app',
    iosBundleId: 'com.example.activesyncApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnH0fJNXGIYVVqb7msH4hgex4atHEaL3c',
    appId: '1:232470263206:web:638cbd69bd48157e17cb67',
    messagingSenderId: '232470263206',
    projectId: 'fyp-sensor-13370',
    authDomain: 'fyp-sensor-13370.firebaseapp.com',
    databaseURL: 'https://fyp-sensor-13370-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fyp-sensor-13370.firebasestorage.app',
    measurementId: 'G-K94HNR2NW4',
  );
}
